name: Release npm package

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '22.x'
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'
      - run: yarn
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run build
      - run: yarn run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
